/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;


import javax.swing.JOptionPane;
import java.sql.Connection;
import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import database.Conexion;
import entidades.Ropa_Tallas;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;
import negocio.RopaControl;
import negocio.SQL_Ropa_Tallas;
import negocio.SQL_Usuarios;

/**
 *
 * @author axel
 */
public class CRUD_ropa extends javax.swing.JFrame {

    /**
     * Creates new form CRUD_ropa
     */
    private final RopaControl control;
    ButtonGroup btnGr;
    ButtonGroup btnGr1;
    //private Usuario user;
    private String imagenRopa;
    private MenuPrincipal menuprincipal;
    
    public CRUD_ropa() {
        //this.user=user;
        //System.out.println(user);
        initComponents();
        control = new RopaControl();
        btnGr = new ButtonGroup();
        btnGr1 = new ButtonGroup();
        btnGr1.add(rbsuperior);
        btnGr1.add(rbinferior);
        btnGr1.add(rbcalzado);
        CargarTabla();
        txtID.setEditable(false);
        //CargarComboTallas();
        jLabel4.setVisible(false);
        cmbtalla.setVisible(false);
        jScrollPane3.setVisible(false);
        txtexistencias.setVisible(false);
        btbagregartalla.setVisible(false);
        imagenRopa = "imagenDefault.jpg";
        btnvolver.setVisible(false);
        //jLabel11.setVisible(false);
        btnlimpiartallas.setVisible(false);
        Marcas();
    }
    int claseSeleccionada =1;

//    CRUD_ropa() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabRopa = new javax.swing.JTabbedPane();
        Listado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaropa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Registros = new javax.swing.JLabel();
        cmbfiltro = new javax.swing.JComboBox<>();
        txtbuscar = new javax.swing.JTextField();
        btnRestablecer = new javax.swing.JButton();
        txtVolver = new javax.swing.JLabel();
        Operaciones = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtpreciocosto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtprecioventa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnseleccionartalla = new javax.swing.JButton();
        btnAgregar1 = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btbagregartalla = new javax.swing.JButton();
        btnlimpiartallas = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtexistencias = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cmbtalla = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cmbtipo1 = new javax.swing.JComboBox<>();
        btnAgregarImagen = new javax.swing.JButton();
        lblRopa = new javax.swing.JLabel();
        rbsuperior = new javax.swing.JRadioButton();
        rbinferior = new javax.swing.JRadioButton();
        rbcalzado = new javax.swing.JRadioButton();
        cbox_marcas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        existencias = new javax.swing.JTextField();
        sexo = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaropa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Descripcion", "P.Costo", "P.Venta", "Ganancia", "Genero", "Marca", "Existencias", "Clase", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaropa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaropaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaropa);

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Listado de Ropa");

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Nuevo");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        Registros.setForeground(new java.awt.Color(0, 153, 153));
        Registros.setText("Registros");

        cmbfiltro.setBackground(new java.awt.Color(0, 153, 153));
        cmbfiltro.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cmbfiltro.setForeground(new java.awt.Color(238, 238, 238));
        cmbfiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Nombre", "Genero", "Marca", "Clase", "Tipo" }));

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        btnRestablecer.setBackground(new java.awt.Color(0, 153, 153));
        btnRestablecer.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnRestablecer.setForeground(new java.awt.Color(238, 238, 238));
        btnRestablecer.setText("Restablecer tabla");
        btnRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerActionPerformed(evt);
            }
        });

        txtVolver.setText("< Volver al menu");
        txtVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ListadoLayout = new javax.swing.GroupLayout(Listado);
        Listado.setLayout(ListadoLayout);
        ListadoLayout.setHorizontalGroup(
            ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListadoLayout.createSequentialGroup()
                .addComponent(txtVolver)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListadoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Registros, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ListadoLayout.createSequentialGroup()
                        .addGroup(ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ListadoLayout.createSequentialGroup()
                                .addGroup(ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ListadoLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(ListadoLayout.createSequentialGroup()
                                                .addComponent(jButton2)
                                                .addGap(29, 29, 29)
                                                .addComponent(btnRestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(ListadoLayout.createSequentialGroup()
                                                .addComponent(cmbfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 89, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        ListadoLayout.setVerticalGroup(
            ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListadoLayout.createSequentialGroup()
                .addComponent(txtVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestablecer)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Registros)
                .addGap(12, 12, 12))
        );

        TabRopa.addTab("Listado", Listado);

        jLabel4.setText("Edicion de Ropa:");

        jLabel5.setText("Nombre:");

        jLabel6.setText("ID");

        jLabel7.setText("Descripcion");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        jLabel8.setText("Clase de Prenda");

        jLabel9.setText("Genero");

        jLabel10.setText("Precio Costo:");

        jLabel11.setText("Precio Venta:");

        jLabel12.setText("Marca:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Talla", "Existencias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        btnseleccionartalla.setBackground(new java.awt.Color(0, 153, 153));
        btnseleccionartalla.setForeground(new java.awt.Color(238, 238, 238));
        btnseleccionartalla.setText("Seleccionar Tallas");
        btnseleccionartalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseleccionartallaActionPerformed(evt);
            }
        });

        btnAgregar1.setBackground(new java.awt.Color(0, 153, 153));
        btnAgregar1.setForeground(new java.awt.Color(238, 238, 238));
        btnAgregar1.setText("Agregar");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(0, 153, 153));
        btnModificar.setForeground(new java.awt.Color(238, 238, 238));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(0, 153, 153));
        btnEliminar.setForeground(new java.awt.Color(238, 238, 238));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(0, 153, 153));
        btnLimpiar.setForeground(new java.awt.Color(238, 238, 238));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btbagregartalla.setBackground(new java.awt.Color(0, 153, 153));
        btbagregartalla.setForeground(new java.awt.Color(238, 238, 238));
        btbagregartalla.setText("Agregar talla");
        btbagregartalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbagregartallaActionPerformed(evt);
            }
        });

        btnlimpiartallas.setBackground(new java.awt.Color(0, 153, 153));
        btnlimpiartallas.setForeground(new java.awt.Color(238, 238, 238));
        btnlimpiartallas.setText("Limpiar");
        btnlimpiartallas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiartallasActionPerformed(evt);
            }
        });

        btnvolver.setBackground(new java.awt.Color(0, 153, 153));
        btnvolver.setForeground(new java.awt.Color(238, 238, 238));
        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        jLabel13.setText("ExistenciasT");

        jLabel14.setText("Talla:");

        cmbtalla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una clase" }));

        jLabel15.setText("Tipo de prenda:");

        cmbtipo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una clase de prenda primero" }));

        btnAgregarImagen.setBackground(new java.awt.Color(0, 153, 153));
        btnAgregarImagen.setForeground(new java.awt.Color(238, 238, 238));
        btnAgregarImagen.setText("Agregar imagen");
        btnAgregarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarImagenActionPerformed(evt);
            }
        });

        lblRopa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rbsuperior.setBackground(new java.awt.Color(255, 255, 255));
        rbsuperior.setText("Superior");
        rbsuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbsuperiorMouseClicked(evt);
            }
        });

        rbinferior.setBackground(new java.awt.Color(255, 255, 255));
        rbinferior.setText("Inferior");
        rbinferior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbinferiorMouseClicked(evt);
            }
        });

        rbcalzado.setBackground(new java.awt.Color(255, 255, 255));
        rbcalzado.setText("Calzado");
        rbcalzado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbcalzadoMouseClicked(evt);
            }
        });

        jLabel2.setText("Existencias");

        sexo.setMaximum(1);
        sexo.setValue(0);

        jLabel3.setText("Femenino");

        jLabel16.setText("Masculino");

        javax.swing.GroupLayout OperacionesLayout = new javax.swing.GroupLayout(Operaciones);
        Operaciones.setLayout(OperacionesLayout);
        OperacionesLayout.setHorizontalGroup(
            OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OperacionesLayout.createSequentialGroup()
                        .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(OperacionesLayout.createSequentialGroup()
                                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(OperacionesLayout.createSequentialGroup()
                                        .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(OperacionesLayout.createSequentialGroup()
                                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane2)))
                                    .addGroup(OperacionesLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbsuperior)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbinferior)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbcalzado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbox_marcas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(OperacionesLayout.createSequentialGroup()
                        .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OperacionesLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtpreciocosto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtprecioventa, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86))
                            .addGroup(OperacionesLayout.createSequentialGroup()
                                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(OperacionesLayout.createSequentialGroup()
                                        .addComponent(btbagregartalla, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnlimpiartallas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnvolver))
                                    .addGroup(OperacionesLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(existencias, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(OperacionesLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbtipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel9))
                            .addGroup(OperacionesLayout.createSequentialGroup()
                                .addComponent(btnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(OperacionesLayout.createSequentialGroup()
                                .addComponent(btnseleccionartalla)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtexistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbtalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OperacionesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnAgregarImagen)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OperacionesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(lblRopa, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))
                        .addContainerGap(4, Short.MAX_VALUE))))
        );
        OperacionesLayout.setVerticalGroup(
            OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(35, 35, 35)
                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rbsuperior)
                    .addComponent(rbinferior)
                    .addComponent(rbcalzado)
                    .addComponent(jLabel12)
                    .addComponent(cbox_marcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OperacionesLayout.createSequentialGroup()
                        .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txtpreciocosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(txtprecioventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnseleccionartalla)
                            .addComponent(jLabel13)
                            .addComponent(txtexistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(cmbtalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btbagregartalla)
                            .addComponent(btnlimpiartallas)
                            .addComponent(btnvolver))
                        .addGap(18, 18, 18)
                        .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cmbtipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(existencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel16)))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addComponent(lblRopa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar1)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnAgregarImagen))
                .addContainerGap())
        );

        TabRopa.addTab("Operaciones", Operaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabRopa)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabRopa)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaropaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaropaMouseClicked
        //Este metodo es para que se le pueda hacer clic a la tabla
        try
        {
            int fila = tablaropa.getSelectedRow();
            int id = Integer.parseInt(tablaropa.getValueAt(fila, 0).toString());
            PreparedStatement ps, ps2;
            ResultSet rs, rs2;
            ResultSetMetaData rsm;
            Connection con = Conexion.getCon();
            Connection con2 = Conexion.getCon();
            String consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.genero, r.marca,r.imagen, cp.nombre, tp.nombre, r.existencias FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda WHERE r.idropa=? ;";
            String consulta_talla = "SELECT t.nombre, rt.existencias FROM Tallas t INNER JOIN ropa_talla rt ON t.idtalla = rt.idtalla INNER JOIN ropa r ON rt.idropa = r.idropa WHERE r.idropa=?";
            ps=con.prepareStatement(consultaSQL);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            while(rs.next())
            {
                txtID.setText(String.valueOf(id));
                txtNombre.setText(rs.getString(2));
                txtDescripcion.setText(rs.getString(3));
                txtpreciocosto.setText(rs.getString(4));
                txtprecioventa.setText(rs.getString(5));
                //cmbtalla.setSelectedItem(rs.getString("talla"));
                if(rs.getString(6).equals("Masculino"))
                {
                    sexo.setValue(0);
                }else if(rs.getString(6).equals("Femenino"))
                {
                    sexo.setValue(1);
                }
                //txtcantidad.setText(rs.getString("cantidad"));
                cbox_marcas.setSelectedItem(rs.getString(7));
                if(rs.getString(9).equals("Superior"))
                {
                    rbsuperior.setSelected(true);
                    TraerTipos(1);
                    TraerTallas(1);
                }else
                {
                    if(rs.getString(9).equals("Inferior"))
                    {
                        rbinferior.setSelected(true);
                        TraerTipos(2);
                        TraerTallas(2);
                    }else if(rs.getString(9).equals("Calzado"))
                    {
                        rbcalzado.setSelected(true);
                        TraerTipos(3);
                        TraerTallas(3);
                    }
                }
                cmbtipo1.setSelectedItem(rs.getString(10));
                
                pintarImagen(lblRopa, "src/presentacion/img/"+rs.getString(8));
                System.out.println(rs.getString(8));
                existencias.setText(rs.getString(11));
                DefaultTableModel modelotabla = (DefaultTableModel) jTable1.getModel();
                modelotabla.setRowCount(0);
                ps2 = con2.prepareStatement(consulta_talla);
                ps2.setInt(1, id);
                rs2 = ps2.executeQuery();
                rsm = rs2.getMetaData();
                int columnas = rsm.getColumnCount();;
                while(rs2.next())
                {
                    Object[] fila2 = new Object[columnas];
                    for(int indice=0; indice<columnas; indice++)
                    {
                        fila2[indice] = rs2.getObject(indice+1);
                    }
                    modelotabla.addRow(fila2);
                }
                //Activar tab 0 y desactivar tab 1
                TabRopa.setSelectedIndex(1); // selecciona el tab(0)
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_tablaropaMouseClicked

    private void btnseleccionartallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseleccionartallaActionPerformed
        System.out.println(claseSeleccionada);
        MostrarOcultarComponentes(false);
    }//GEN-LAST:event_btnseleccionartallaActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        String resp = null, sexo;
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes de ingresar un nombre a la prenda");
            txtNombre.requestFocus();
            return;
        }
        if (txtDescripcion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes de ingresar una descripcion a la prenda");
            txtDescripcion.requestFocus();
            return;
        }
        if (imagenRopa.equals("imagenDefault.jpg")) {
            JOptionPane.showMessageDialog(null, "Debes ingresar una imagen del producto");
            return;
        }
        if (Integer.parseInt(existencias.getText()) < 0) {
            JOptionPane.showMessageDialog(null, "no puede a ver existencias negativas");
        } else {
            boolean bandera = false;
            double ganancia = 0, precio_costo = 0, precio_venta = 0;
            try {

                precio_costo = Double.parseDouble(txtpreciocosto.getText());
                precio_venta = Double.parseDouble(txtprecioventa.getText());
                if (precio_costo > 0 && precio_venta > 0) {
                    if (precio_venta > precio_costo) {
                        ganancia = precio_venta - precio_costo;
                        bandera = true;
                    } else {
                        JOptionPane.showMessageDialog(null, "El precio de costo no debe ser mayor al de venta");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Los precios deben ser mayores a cero");
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Debe ingresar un valor numerico en el precio");
            }
            if (bandera) {
                if (cmbtalla.getSelectedItem().toString().equals("Seleccione una clase")) {
                    JOptionPane.showMessageDialog(null, "Debe seleccionar una talla");
                } else {
                    sexo = (this.sexo.getValue() == 0) ? "Masculino" : "Femenino";
                    try {
                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        if (model.getRowCount() > 0) {
                            /*
                                     for (int i = 0; i<model.getRowCount(); i++) {
                                        final String col1 = (String) model.getValueAt(i, 0);
                                        final String col2 = (String) model.getValueAt(i, 1);
                                        System.out.println("Talla: " + col1 + " Existencia: " + col2);
                                    }*/

                        } else {
                            JOptionPane.showMessageDialog(null, "Debe Agregar las tallas");
                        }
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Debe ingresar un valor numerico en las existencias");
                    }
                    String marca = cbox_marcas.getSelectedItem().toString();
                    if (marca.equals("Seleccione una opcion")) {
                        JOptionPane.showMessageDialog(null, "Debes de seleccionar una marca");
                    } else {
                        //mod.setMarca(marca);
                        int clase = -1;
                        if (rbsuperior.isSelected() == true) {
                            clase = 1;
                        } else {
                            if (rbinferior.isSelected() == true) {
                                clase = 2;
                            } else {
                                if (rbcalzado.isSelected() == true) {
                                    clase = 3;
                                }
                            }
                        }
                        if (!cmbtipo1.getSelectedItem().toString().equals("Seleccione una clase de prenda primero")) {
                            // mod.setIdtipoprenda(traerIDTipoPrenda(cmbtipo1.getSelectedItem().toString(), clase));
                        } else {
                            JOptionPane.showMessageDialog(null, "Debe seleccionar un tipo de ropa");
                        }
                        resp = control.insertar(txtNombre.getText(), txtDescripcion.getText(),
                                precio_costo, precio_venta, ganancia, sexo,
                                cbox_marcas.getSelectedItem().toString(), imagenRopa,
                                traerIDTipoPrenda(cmbtipo1.getSelectedItem().toString(), clase), Integer.parseInt(existencias.getText()));
                        if (resp.equals("OK")) {
                            imagen();
                            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                            if (model.getRowCount() > 0) {
                                SQL_Ropa_Tallas sqlropatallas = new SQL_Ropa_Tallas();
                                for (int i = 0; i < model.getRowCount(); i++) {

                                    Ropa_Tallas rt = new Ropa_Tallas();
                                    rt.setIdropa(traerUltimoIDRopa());
                                    rt.setIdtalla(traerIDTalla(model.getValueAt(i, 0).toString(), clase));
                                    rt.setExistencias(Integer.parseInt(model.getValueAt(i, 1).toString()));
                                    sqlropatallas.Agregar(rt);
                                }
                            }
                            //una vez que guardo la ropa guardara las tallas

                            JOptionPane.showMessageDialog(this, "Registro guardado", "Registro", JOptionPane.INFORMATION_MESSAGE);
                            TabRopa.setSelectedIndex(0);
                            Limpiar();
                            CargarTabla();
                        } else {
                            JOptionPane.showMessageDialog(this, "Error al guardar el registro", "Registro", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int id = 0;
        boolean ban = false;
        try {
            id = Integer.parseInt(txtID.getText());
            ban = true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Seleccione un elemento de la tabla para obtener un id");
        }
        
        String resp = null, sexo;
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes de ingresar un nombre a la prenda");
            txtNombre.requestFocus();
            return;
        }
        if (txtDescripcion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes de ingresar una descripcion a la prenda");
            txtDescripcion.requestFocus();
            return;
        }
        if (imagenRopa.equals("imagenDefault.jpg")) {
            JOptionPane.showMessageDialog(null, "Debes ingresar una imagen del producto");
            return;
        }
        if (Integer.parseInt(existencias.getText()) < 0) {
            JOptionPane.showMessageDialog(null, "no puede a ver existencias negativas");
        } else {
            boolean bandera = false;
            double ganancia = 0, precio_costo = 0, precio_venta = 0;
            try {

                precio_costo = Double.parseDouble(txtpreciocosto.getText());
                precio_venta = Double.parseDouble(txtprecioventa.getText());
                if (precio_costo > 0 && precio_venta > 0) {
                    if (precio_venta > precio_costo) {
                        ganancia = precio_venta - precio_costo;
                        bandera = true;
                    } else {
                        JOptionPane.showMessageDialog(null, "El precio de costo no debe ser mayor al de venta");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Los precios deben ser mayores a cero");
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Debe ingresar un valor numerico en el precio");
            }
            if (bandera) {
                if (cmbtalla.getSelectedItem().toString().equals("Seleccione una clase")) {
                    JOptionPane.showMessageDialog(null, "Debe seleccionar una talla");
                } else {
                    sexo = (this.sexo.getValue() == 0) ? "Masculino" : "Femenino";
                    try {
                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        if (model.getRowCount() > 0) {
                            /*
                                     for (int i = 0; i<model.getRowCount(); i++) {
                                        final String col1 = (String) model.getValueAt(i, 0);
                                        final String col2 = (String) model.getValueAt(i, 1);
                                        System.out.println("Talla: " + col1 + " Existencia: " + col2);
                                    }*/

                        } else {
                            JOptionPane.showMessageDialog(null, "Debe Agregar las tallas");
                        }
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Debe ingresar un valor numerico en las existencias");
                    }
                    String marca = cbox_marcas.getSelectedItem().toString();
                    if (marca.equals("Seleccione una opcion")) {
                        JOptionPane.showMessageDialog(null, "Debes de seleccionar una marca");
                    } else {
                        //mod.setMarca(marca);
                        int clase = -1;
                        if (rbsuperior.isSelected() == true) {
                            clase = 1;
                        } else {
                            if (rbinferior.isSelected() == true) {
                                clase = 2;
                            } else {
                                if (rbcalzado.isSelected() == true) {
                                    clase = 3;
                                }
                            }
                        }
                        if (!cmbtipo1.getSelectedItem().toString().equals("Seleccione una clase de prenda primero")) {
                            // mod.setIdtipoprenda(traerIDTipoPrenda(cmbtipo1.getSelectedItem().toString(), clase));
                        } else {
                            JOptionPane.showMessageDialog(null, "Debe seleccionar un tipo de ropa");
                        }
                        resp = control.actualizar(Integer.parseInt(txtID.getText()),txtNombre.getText(), txtDescripcion.getText(),
                                precio_costo, precio_venta, ganancia, sexo,
                                cbox_marcas.getSelectedItem().toString(), imagenRopa,
                                traerIDTipoPrenda(cmbtipo1.getSelectedItem().toString(), clase), Integer.parseInt(existencias.getText()));
                        if (resp.equals("OK")) {
                            imagen();
                            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                            if (model.getRowCount() > 0) {
                                Ropa_Tallas rt = new Ropa_Tallas();
                                SQL_Ropa_Tallas sqlropatallas = new SQL_Ropa_Tallas();
                                sqlropatallas.Eliminar(id);
                                for (int i = 0; i < model.getRowCount(); i++) {

                                    rt.setIdropa(id);
                                    rt.setIdtalla(traerIDTalla(model.getValueAt(i, 0).toString(), clase));
                                    rt.setExistencias(Integer.parseInt(model.getValueAt(i, 1).toString()));
                                    sqlropatallas.Agregar(rt);
                                }
                            }
                            //una vez que guardo la ropa guardara las tallas

                            JOptionPane.showMessageDialog(this, "Registro guardado", "Registro", JOptionPane.INFORMATION_MESSAGE);
                            TabRopa.setSelectedIndex(0);
                            Limpiar();
                            CargarTabla();
                        } else {
                            JOptionPane.showMessageDialog(this, "Error al guardar el registro", "Registro", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            }
        }
        /*
        SQL_Ropa modSql = new SQL_Ropa();
        Ropa mod = new Ropa();
        String nombre = txtNombre.getText();
        if (ban) {
            if (nombre.equals("")) {
                JOptionPane.showMessageDialog(null, "Debes de ingresar un nombre a la prenda");
            } else {
                mod.setNombre(nombre);
                String descripcion = txtDescripcion.getText();
                if (descripcion.equals("")) {
                    JOptionPane.showMessageDialog(null, "Debes de ingresar una descripcion a la prenda");
                } else {
                    mod.setDescripcion(descripcion);
                    String imagen = imagenRopa;
                    if (imagen.equals("imagenDefault.jpg")) {
                        JOptionPane.showMessageDialog(null, "Debes ingresar una imagen del producto");
                    } else {
                        mod.setImagen(imagen);
                        int existencias = Integer.parseInt(this.existencias.getText());
                        if (existencias < 0) {
                            JOptionPane.showMessageDialog(null, "las existencias deben ser mayor a 0");
                        } else {
                            mod.setExistencias(existencias);
                            if (txtpreciocosto.getText().equals("") && txtprecioventa.getText().equals("")) {
                                JOptionPane.showMessageDialog(null, "Debe ingresar valores en los precios");
                            } else {
                                boolean bandera = false;
                                try {
                                    double precio_costo = Double.parseDouble(txtpreciocosto.getText());
                                    double precio_venta = Double.parseDouble(txtprecioventa.getText());
                                    if (precio_costo > 0 && precio_venta > 0) {
                                        if (precio_venta > precio_costo) {
                                            mod.setPrecio_costo(precio_costo);
                                            mod.setPrecio_venta(precio_venta);
                                            mod.setGanancia(precio_venta - precio_costo);
                                            bandera = true;
                                        } else {
                                            JOptionPane.showMessageDialog(null, "El precio de costo no debe ser mayor al de venta");
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Los precios deben ser mayores a cero");
                                    }
                                } catch (NumberFormatException e) {
                                    JOptionPane.showMessageDialog(null, "Debe ingresar un valor numerico en el precio");
                                }
                                if (bandera) {
                                    if (cmbtalla.getSelectedItem().toString().equals("Seleccione una clase")) {
                                        JOptionPane.showMessageDialog(null, "Debe seleccionar una talla");
                                    } else {
                                        String sexo;
                                        if (rbmasculino.isSelected() == true) {
                                            sexo = "Masculino";
                                            mod.setGenero(sexo);
                                        } else {
                                            if (rbfemenino.isSelected() == true) {
                                                sexo = "Femenino";
                                                mod.setGenero(sexo);
                                            } else {
                                                JOptionPane.showMessageDialog(null, "Debe seleccionar un genero");
                                            }
                                        }
                                        try {
                                            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                                            if (model.getRowCount() > 0) {
                                                /*
                                        for (int i = 0; i<model.getRowCount(); i++) {
                                            final String col1 = (String) model.getValueAt(i, 0);
                                            final String col2 = (String) model.getValueAt(i, 1);
                                            System.out.println("Talla: " + col1 + " Existencia: " + col2);
                                        }
                                                 
                                            } else {
                                                JOptionPane.showMessageDialog(null, "Debe Agregar las tallas");
                                            }
                                        } catch (NumberFormatException e) {
                                            JOptionPane.showMessageDialog(null, "Debe ingresar un valor numerico en las existencias");
                                        }
                                        String marca = cbox_marcas.getSelectedItem().toString();
                                        if (marca.equals("")) {
                                            JOptionPane.showMessageDialog(null, "Debes de ingresar una marca");
                                        } else {
                                            mod.setMarca(marca);
                                            int clase = -1;
                                            if (rbsuperior.isSelected() == true) {
                                                clase = 1;
                                            } else {
                                                if (rbinferior.isSelected() == true) {
                                                    clase = 2;
                                                } else {
                                                    if (rbcalzado.isSelected() == true) {
                                                        clase = 3;
                                                    }
                                                }
                                            }
                                            if (!cmbtipo1.getSelectedItem().toString().equals("Seleccione una clase de prenda primero")) {
                                                mod.setIdtipoprenda(traerIDTipoPrenda(cmbtipo1.getSelectedItem().toString(), clase));
                                            } else {
                                                JOptionPane.showMessageDialog(null, "Debe seleccionar un tipo de ropa");
                                            }
                                            mod.setIdropa(id);
                                            if (modSql.Modificar(mod)) {
                                                //consulta para traer el ultimo id deROPA REGISTRADO
                                                //SELECT MAX(idropa) AS 'idropa' FROM ropa
                                                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                                                if (model.getRowCount() > 0) {
                                                    Ropa_Tallas rt = new Ropa_Tallas();
                                                    SQL_Ropa_Tallas sqlropatallas = new SQL_Ropa_Tallas();
                                                    sqlropatallas.Eliminar(id);
                                                    for (int i = 0; i < model.getRowCount(); i++) {

                                                        rt.setIdropa(id);
                                                        rt.setIdtalla(traerIDTalla(model.getValueAt(i, 0).toString(), clase));
                                                        rt.setExistencias(Integer.parseInt(model.getValueAt(i, 1).toString()));
                                                        sqlropatallas.Agregar(rt);
                                                    }
                                                }
                                                //una vez que guardo la ropa guardara las tallas

                                                JOptionPane.showMessageDialog(this, "Registro guardado", "Registro", JOptionPane.INFORMATION_MESSAGE);
                                                TabRopa.setSelectedIndex(0);
                                                Limpiar();
                                                CargarTabla();
                                            } else {
                                                JOptionPane.showMessageDialog(this, "Error al guardar el registro", "Registro", JOptionPane.ERROR_MESSAGE);
                                            }
                                        }
                                    }
                                }
                            }
                        }

                    }
                }
            }
        }*/
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int id = 0;
        try
        {
            id = Integer.parseInt(txtID.getText());
        }catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Seleccione un elemento de la tabla para obtener un id");
        }
        if(!txtID.getText().equals(""))
        {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            if(model.getRowCount()>0){/*
                for (int i = 0; i<model.getRowCount(); i++) {
                    final String col1 = (String) model.getValueAt(i, 0);
                    final String col2 = (String) model.getValueAt(i, 1);
                    System.out.println("Talla: " + col1 + " Existencia: " + col2);
                }*/
                //DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                if(model.getRowCount()>0){
                    SQL_Ropa_Tallas sqlropatallas = new SQL_Ropa_Tallas();
                    for (int i = 0; i<model.getRowCount(); i++)
                    {
                        Ropa_Tallas rt =new Ropa_Tallas();
                        rt.setIdropa(id);
                        rt.setIdtalla(traerIDTalla((String) model.getValueAt(i, 0), 0));
                        rt.setExistencias(Integer.parseInt(model.getValueAt(i, 1).toString()));
                        sqlropatallas.Eliminar(id);
                    }
                }
                try
                {
                    Connection con = Conexion.getCon();
                    PreparedStatement ps = con.prepareStatement("DELETE FROM ropa WHERE idropa=?");
                    ps.setInt(1, Integer.parseInt(txtID.getText()));
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Registro eliminado", "Registro", JOptionPane.INFORMATION_MESSAGE);
                    TabRopa.setSelectedIndex(0);
                    Limpiar();
                    CargarTabla();
                }
                catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(this, "Error al eliminar el registro", "Registro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        Limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btbagregartallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbagregartallaActionPerformed
        if(!(cmbtalla.getSelectedItem().toString().equals("Seleccione una clase")))
        {
            int existencias = Integer.parseInt(txtexistencias.getText());
            if(existencias > 0)
            {
                try
                {
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    int columnas = model.getRowCount();
                    boolean existe =false;
                    for (int i = 0; i<columnas; i++) {
                        if(model.getValueAt(i, 0).toString().equalsIgnoreCase(cmbtalla.getSelectedItem().toString())){
                            existe = true;
                            break;
                        }
                    }
                    if (!existe) {
                        Object[] row = { cmbtalla.getSelectedItem(), existencias};
                        model.addRow(row);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Ya tienes esta talla registradas");
                    }

                }catch(NumberFormatException e)
                {
                    JOptionPane.showMessageDialog(null, "Debes ingresar un valor numerico en las existencias");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No puedes agregar existencias negativas");
            }
        }else
        {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una talla");
        }
    }//GEN-LAST:event_btbagregartallaActionPerformed

    private void btnlimpiartallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiartallasActionPerformed
        LimpiarTablaTallas();
    }//GEN-LAST:event_btnlimpiartallasActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        MostrarOcultarComponentes(true);
    }//GEN-LAST:event_btnvolverActionPerformed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        /*if(evt.getExtendedKeyCode()==KeyEvent.VK_ENTER)
        {
            btnbuscarActionPerformed(java.awt.event.ActionEvent evt);
            se crearia un nuevo metodo con lo del boton de buscar
        }*/
    }//GEN-LAST:event_txtbuscarKeyPressed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        DefaultTableModel modelotabla = (DefaultTableModel) tablaropa.getModel();
        modelotabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        String busqueda = txtbuscar.getText();
        if(busqueda.trim().equals(""))
        {
            CargarTabla();
        }
        else
        {
            int columnas;
            int[] anchos = {30,100,150,40,30,60,40,70,80,124,50};
            for(int i = 0; i<tablaropa.getColumnCount(); i++)
            {
                tablaropa.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }
            try
            {
                Connection con = Conexion.getCon();
                String consultaSQL = "";
                String filtro = cmbfiltro.getSelectedItem().toString();
                if(filtro.equals("Id"))
                {
                    consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.ganancia, r.genero, r.marca, cp.nombre, tp.nombre,r.existencias FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda WHERE r.idropa = '"+busqueda+"' ";
                }else
                {
                    if(filtro.equals("Nombre"))
                    {
                        consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.ganancia, r.genero, r.marca, cp.nombre, tp.nombre,r.existencias FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda WHERE r.nombre like '%"+busqueda+"%' ";
                    }else
                    {
                        if(filtro.equals("Genero"))
                        {
                            consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.ganancia, r.genero, r.marca, cp.nombre, tp.nombre,r.existencias FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda WHERE r.genero like '%"+busqueda+"%' ";
                        }
                        else
                        {
                            if(filtro.equals("Marca"))
                            {
                                consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.ganancia, r.genero, r.marca, cp.nombre, tp.nombre,r.existencias FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda WHERE r.marca like '%"+busqueda+"%' ";
                            }
                            else
                            {
                                if(filtro.equals("Clase"))
                                {
                                    consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.ganancia, r.genero, r.marca, cp.nombre, tp.nombre,r.existencias FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda WHERE cp.nombre like '%"+busqueda+"%' ";
                                }
                                else
                                {
                                    if(filtro.equals("Tipo"))
                                    {
                                        consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.ganancia, r.genero, r.marca, cp.nombre, tp.nombre, r.existencias FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda WHERE tp.nombre like '%"+busqueda+"%' ";
                                    }
                                }
                            }
                        }
                    }
                }
                ps = con.prepareStatement(consultaSQL);
                rs = ps.executeQuery();
                rsmd = rs.getMetaData();
                columnas = rsmd.getColumnCount();
                while(rs.next())
                {
                    Object[] fila = new Object[columnas];
                    for(int indice=0; indice<columnas; indice++)
                    {
                        fila[indice] = rs.getObject(indice+1);
                    }
                    modelotabla.addRow(fila);
                }
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null, e.toString());
            }
        }
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void btnRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerActionPerformed
        CargarTabla();
    }//GEN-LAST:event_btnRestablecerActionPerformed

    private void rbsuperiorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbsuperiorMouseClicked
        TraerTallas(1);
        TraerTipos(1);
        claseSeleccionada=1;
        LimpiarTablaTallas();
    }//GEN-LAST:event_rbsuperiorMouseClicked

    private void rbinferiorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbinferiorMouseClicked
        TraerTallas(2);
        TraerTipos(2);
        claseSeleccionada=2;
        LimpiarTablaTallas();
    }//GEN-LAST:event_rbinferiorMouseClicked

    private void rbcalzadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbcalzadoMouseClicked
        TraerTallas(3);
        TraerTipos(3);
        claseSeleccionada=3;
        LimpiarTablaTallas();
    }//GEN-LAST:event_rbcalzadoMouseClicked

    private void btnAgregarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarImagenActionPerformed
        String ruta;
        //crear un obj que permita seleccionar un archvio
        JFileChooser jf = new JFileChooser();
        //establecer un filtro para seleccion de imagenes
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Gif,JPG,PNG", "gif","jpg","png");
        // establecer el filtro al objeto jf
        jf.setFileFilter(filtro);
        // abrir el cuadro de dialogo
        int resp = jf.showOpenDialog(this);
        // validar la respuesta
        if(resp == JFileChooser.APPROVE_OPTION){
            // obtener la ruta del archivo seleccionado
            ruta = jf.getSelectedFile().getPath();
            // obtener el nombre del archivo seleccionado
            imagenRopa = jf.getSelectedFile().getName();
            
            // pintar la imagen que selecciono el usuario
            pintarImagen(lblRopa,ruta);
        }
    }//GEN-LAST:event_btnAgregarImagenActionPerformed

    private void txtVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVolverMouseClicked
        if(menuprincipal == null)
        {
           menuprincipal = new MenuPrincipal();
           menuprincipal.setVisible(true);
           dispose();
        }
        /*MenuPrincipal obm = new MenuPrincipal(user);
        obm.setVisible(true);
        MenuPrincipal.frmCusers = null;
        dispose();*/
    }//GEN-LAST:event_txtVolverMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        TabRopa.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2MouseClicked

    public void pintarImagen(JLabel lbl, String ruta){
         ImageIcon imagen = new ImageIcon(ruta);
         Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_SMOOTH));
         lbl.setIcon(icono);
         repaint();   
     }
    private void TraerTallas(int idClase){
        try
        {
            Connection con = Conexion.getCon();
            String consultaSQL = "select t.idtalla,t.nombre,rt.existencias from Tallas t inner join ropa_talla rt on t.idtalla = rt.idtalla where idclasePrenda=?";
            PreparedStatement ps;
            ResultSet rs;
            ps = con.prepareStatement(consultaSQL);
            ps.setInt(1, idClase);
            rs = ps.executeQuery();
            cmbtalla.removeAllItems();
            while(rs.next())
            {
               cmbtalla.addItem(rs.getString(2));
               txtexistencias.setText(rs.getString(3));
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    public void Marcas(){
        List<String> marcas = new ArrayList();
        cbox_marcas.addItem("Seleccione una opcion");
        marcas=control.Marcas();
        for (int i=0; i<marcas.size();i++) {
            cbox_marcas.addItem(marcas.get(i));
        }
    }
    private void TraerTipos(int idClase)
    {
        try
        {
            Connection con = Conexion.getCon();
            String consultaSQL = "select idTipoPrenda,nombre from TipoPrenda where idclasePrenda=?";
            PreparedStatement ps;
            ResultSet rs;
            ps = con.prepareStatement(consultaSQL);
            ps.setInt(1, idClase);
            rs = ps.executeQuery();
            cmbtipo1.removeAllItems();
            while(rs.next())
            {
               cmbtipo1.addItem(rs.getString(2));
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    private void imagen(){
        String ruta;
        //crear un obj que permita seleccionar un archvio
        JFileChooser jf = new JFileChooser();
        //establecer un filtro para seleccion de imagenes
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Gif,JPG,PNG", "gif","jpg","png");
        // establecer el filtro al objeto jf
        jf.setFileFilter(filtro);
        // abrir el cuadro de dialogo
        int resp = jf.showOpenDialog(this);
        // validar la respuesta
        if(resp == JFileChooser.APPROVE_OPTION){
            // obtener la ruta del archivo seleccionado
            ruta = jf.getSelectedFile().getPath();
            // obtener el nombre del archivo seleccionado
            imagenRopa = jf.getSelectedFile().getName();
            
            //copiar archivo y pegarlo
            String destino = "src/presentacion/img/";
            try {
                copiarpegarimagen(ruta, destino,imagenRopa);
            } catch (IOException ex) {
                Logger.getLogger(CRUD_ropa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void MostrarOcultarComponentes(boolean accion){
        jLabel5.setVisible(accion);
        
        jLabel7.setVisible(accion);
        jLabel9.setVisible(accion);
        cmbtipo1.setVisible(accion);
        cbox_marcas.setVisible(accion);
        btnAgregarImagen.setVisible(accion);
        btnEliminar.setVisible(accion);
        btnLimpiar.setVisible(accion);
        btnModificar.setVisible(accion);
        btnseleccionartalla.setVisible(accion);
        Registros.setVisible(accion);
        txtpreciocosto.setVisible(accion);
        jLabel6.setVisible(accion);
        txtprecioventa.setVisible(accion);
        
        btbagregartalla.setVisible(!accion);
        txtexistencias.setVisible(!accion);
        jLabel4.setVisible(!accion);
        cmbtalla.setVisible(!accion);
        jScrollPane3.setVisible(!accion);
        btnvolver.setVisible(!accion);
        //jLabel11.setVisible(!accion);
        btnlimpiartallas.setVisible(!accion);
    }
    private void copiarpegarimagen(String src, String dst,String nombre) throws IOException{
        try{
            InputStream in = new FileInputStream(src);
            OutputStream out = new FileOutputStream(dst+nombre);
            
            byte[] b = new byte[1024];
            int i;
            while((i = in.read(b))>0){
                out.write(b,0,i);
            }
        }catch(FileNotFoundException e){
            e.printStackTrace();
        }
    }
     private void CargarTabla()
    {
        tablaropa.setModel(control.listar());
        
        establecerAnchoColumnas(tablaropa);
        
        TableRowSorter modeloOrdenado = new TableRowSorter(tablaropa.getModel());
        tablaropa.setRowSorter(modeloOrdenado);
        
        Registros.setText("Mostrados " + control.total());
    }
     private void establecerAnchoColumnas(JTable tabla){
         int id = 0;
         int Nombre = 80;
         int Descripcion = 100;
         int PCosto = 20;
         int PVenta = 20;
         int Genero = 50;
         int Marca = 50;
         int Existencias = 20;
         int Clase = 50;
         int Tipo = 50;
         TableColumn columna;
         DefaultTableCellRenderer modelocentrar = new DefaultTableCellRenderer();
         modelocentrar.setHorizontalAlignment(SwingConstants.CENTER);
         for (int i=0; i<tabla.getColumnCount(); i++){
            switch(i){
                case 0: // ID esta oculto
                    columna=tabla.getColumnModel().getColumn(i);
                    columna.setPreferredWidth(id);
                    //columna.setMaxWidth(tamEstatus);
                    columna.setMinWidth(id);
                    break;
                    /*
                    columna=tabla.getColumnModel().getColumn(i);
                    columna.setMaxWidth(id);
                    columna.setMinWidth(id);
                    tabla.getTableHeader().getColumnModel().getColumn(i).setMaxWidth(0);
                    tabla.getTableHeader().getColumnModel().getColumn(i).setMinWidth(0);
                    break;*/
                case 1:
                    columna=tabla.getColumnModel().getColumn(i);
                    columna.setPreferredWidth(Nombre);
                    //columna.setMaxWidth(tamNombre);
                    columna.setMinWidth(Nombre);
                    break;
                case 2:
                    columna=tabla.getColumnModel().getColumn(i);
                    columna.setPreferredWidth(Descripcion);
                    //columna.setMaxWidth(tamDescripcion);
                    columna.setMinWidth(Descripcion);
                    break;
                case 3:
                    columna=tabla.getColumnModel().getColumn(i);
                    columna.setCellRenderer(modelocentrar);  //table.getColumnModel().getColumn(col).setCellRenderer(modelocentrar);
                    columna.setPreferredWidth(PCosto);
                    //columna.setMaxWidth(tamConDescuento);
                    columna.setMinWidth(PCosto);
                    break;
                case 4:
                    columna=tabla.getColumnModel().getColumn(i);
                    columna.setPreferredWidth(PVenta);
                    //columna.setMaxWidth(tamDescuento);
                    columna.setMinWidth(PVenta);
                    break;
                case 5:
                    columna=tabla.getColumnModel().getColumn(i);
                    columna.setPreferredWidth(Genero);
                    //columna.setMaxWidth(tamImagen);
                    columna.setMinWidth(Genero);
                    break;
                case 6:
                    columna=tabla.getColumnModel().getColumn(i);
                    columna.setPreferredWidth(Marca);
                    //columna.setMaxWidth(tamEstatus);
                    columna.setMinWidth(Marca);
                    break;
                case 7:
                    columna=tabla.getColumnModel().getColumn(i);
                    columna.setPreferredWidth(Existencias);
                    //columna.setMaxWidth(tamEstatus);
                    columna.setMinWidth(Existencias);
                    break;
                case 8:
                    columna=tabla.getColumnModel().getColumn(i);
                    columna.setPreferredWidth(Clase);
                    //columna.setMaxWidth(tamEstatus);
                    columna.setMinWidth(Clase);
                    break;
                case 9:
                    columna=tabla.getColumnModel().getColumn(i);
                    columna.setPreferredWidth(Tipo);
                    //columna.setMaxWidth(tamEstatus);
                    columna.setMinWidth(Tipo);
                    break;
            }
        }
        
        tabla.setRowHeight(30);
     }
    private void Limpiar()
    {
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtpreciocosto.setText("");
        cmbtalla.setSelectedItem("Seleccione");
        cbox_marcas.removeAllItems();
        Marcas();
        btnGr.clearSelection();
        btnGr1.clearSelection();
        cmbtipo1.setVisible(true);
        txtID.setText("");
        cmbtalla.removeAllItems();
        cmbtalla.addItem("Seleccione una clase");
        cmbtalla.setSelectedItem("Seleccione una clase");
        cmbtipo1.addItem("Seleccione una clase de prenda primero");
        cmbtipo1.setSelectedItem("Seleccione una clase de prenda primero");
        txtexistencias.setText("");
        txtprecioventa.setText("");
        lblRopa.setText("");
        existencias.setText("0");
        LimpiarTablaTallas();
    }
    private void LimpiarTablaTallas()
    {
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        int a = jTable1.getRowCount()-1;
        for (int i = a; i >= 0; i--) 
        {          
            tb.removeRow(tb.getRowCount()-1);
        }
        txtexistencias.setText("");
    }
    private int traerIDTipoPrenda(String nombre, int clase) {
        PreparedStatement ps = null;
        Connection con = Conexion.getCon();
        ResultSet rs;
        String consultaSQL = "Select idTipoPrenda from TipoPrenda where nombre=? and idclaseprenda=? ;";
        try {
            ps = con.prepareStatement(consultaSQL);
            ps.setString(1, nombre);
            ps.setInt(2, clase);
            rs = ps.executeQuery();
            if (rs.next()) {
                return rs.getInt(1);
            }
            return -1;
        } catch (SQLException ex) {
            Logger.getLogger(SQL_Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            return -1;
        }
    }

    private int traerIDTalla(String nombre, int clase) {
        PreparedStatement ps = null;
        Connection con = Conexion.getCon();
        ResultSet rs;
        String consultaSQL = "Select idtalla from Tallas where nombre=? and idclasePrenda=? ;";
        try {
            ps = con.prepareStatement(consultaSQL);
            ps.setString(1, nombre);
            ps.setInt(2, clase);
            rs = ps.executeQuery();
            if (rs.next()) {
                return rs.getInt(1);
            }
            return -1;
        } catch (SQLException ex) {
            Logger.getLogger(SQL_Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            return -1;
        }
    }

    private int traerUltimoIDRopa() {
        PreparedStatement ps = null;
        Connection con = Conexion.getCon();
        ResultSet rs;
        String consultaSQL = "Select MAX(idropa) from ropa;";
        try {
            ps = con.prepareStatement(consultaSQL);
            rs = ps.executeQuery();
            if (rs.next()) {
                return rs.getInt(1);
            }
            return -1;
        } catch (SQLException ex) {
            Logger.getLogger(SQL_Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            return -1;
        }
    }
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD_ropa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD_ropa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD_ropa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD_ropa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD_ropa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Listado;
    private javax.swing.JPanel Operaciones;
    private javax.swing.JLabel Registros;
    private javax.swing.JTabbedPane TabRopa;
    private javax.swing.JButton btbagregartalla;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnAgregarImagen;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRestablecer;
    private javax.swing.JButton btnlimpiartallas;
    private javax.swing.JButton btnseleccionartalla;
    private javax.swing.JButton btnvolver;
    private javax.swing.JComboBox<String> cbox_marcas;
    private javax.swing.JComboBox<String> cmbfiltro;
    private javax.swing.JComboBox<String> cmbtalla;
    private javax.swing.JComboBox<String> cmbtipo1;
    private javax.swing.JTextField existencias;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblRopa;
    private javax.swing.JRadioButton rbcalzado;
    private javax.swing.JRadioButton rbinferior;
    private javax.swing.JRadioButton rbsuperior;
    private javax.swing.JSlider sexo;
    private javax.swing.JTable tablaropa;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JLabel txtVolver;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtexistencias;
    private javax.swing.JTextField txtpreciocosto;
    private javax.swing.JTextField txtprecioventa;
    // End of variables declaration//GEN-END:variables
}
